modLoader="javafml"
loaderVersion="[4,)"
license="MMPL-1.0.1"
issueTrackerURL="https://github.com/The-Mystora-Project/VoxLib/issues"

[[mods]]
modId="voxlib"
version="${version}"
displayName="Mystery2099's VoxLib"
displayURL="https://github.com/The-Mystora-Project/VoxLib"
logoFile="assets/voxlib/icon.png"
authors="Mystery2099"
description="A library for creating, combining, transforming, debugging, and reusing voxel shapes."

[[dependencies.voxlib]]
modId="neoforge"
type="required"
versionRange="[21.1.250,21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.voxlib]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
