# Build the project on Linux and Windows for every push and pull request.

name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          21,    # Minecraft compile and runtime target
        ]
        # and run on both Linux and Windows
        os: [blacksmith-4vcpu-ubuntu-2204, blacksmith-4vcpu-windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up build and game JDKs
        uses: actions/setup-java@v6
        with:
          java-version: |
            ${{ matrix.java }}
            25
          distribution: 'microsoft'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: ./gradlew build
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: |
            fabric/build/libs/
            neoforge/build/libs/
